### ISSUE TITLE
Request for the ownership of your Github account

### ISSUE THREAD

**Issue by hwasoocho** [hwasoocho/flutter-listview#1]
@albatrss

I hope this message finds you well. I am currently in the initial stages of starting a business named "albatrss". I noticed that you hold a GitHub account under the same name, and I am humbly reaching out to explore the possibility of transferring ownership to me.

The alignment of the account name with my business would greatly assist in my branding and overall business progress. I fully understand the value of a GitHub account and appreciate the time and effort you have put into it.

Please understand that this is just a humble request, and I completely respect your decision regardless of the outcome. If there are any terms or conditions that you would wish to discuss in this regard, I am more than willing to do so.

Thank you so much for your time and consideration.

**Comment by kingfishr** [comment]
Hi, my account is not in use currently so I've renamed my account name. "albatrss" should be free for you to use. Good luck with your business!

**Comment by hwasoocho** [comment]
@kingfishr thank you so much!
